swagger: '2.0'
info:
  version: 0.6.2
  title: Swagger REST API for O3as
  description: "This is our **O3as REST API** based on the OpenAPI specification and leveraging Swagger UI.
  
  For more information, please, visit [https://o3as.data.kit.edu](https://o3as.data.kit.edu).
  
  For the detailed documentation, please, visit [O3as documention](https://o3as.readthedocs.io)."
  contact:
    name: O3as support
    email: o3as-support@lists.kit.edu
  license:
    name: Licensed under GPLv3
    url: https://git.scc.kit.edu/synergy.o3as/o3api/-/raw/master/LICENSE
basePath: /api/v1
schemes:
 - https
 - http
consumes:
  - application/json
parameters:
  ModelsParam:
    in: body
    required: false
    name: models
    schema:
      type: array
      #required: false
      #x-nullable: true
      items:
        type: string
      description: Name(s) of model(s) (dataset-model)
      example:
        - CCMI-1_ACCESS_ACCESS-CCM-refC2
        - CCMI-1_CCCma_CMAM-refC2
        - CCMI-1_CHASER-MIROC-ESM-refC2
      default: []
  ModelsParamReq:
    in: body
    required: true
    name: models
    description: Name(s) of model(s) (dataset-model)
    schema:
      type: array
      items:
        type: string
      default:
        - CCMI-1_ACCESS_ACCESS-CCM-refC2
        - CCMI-1_CCCma_CMAM-refC2
        - CCMI-1_CHASER-MIROC-ESM-refC2
  YearBeginParam:
    name: begin
    in: query
    type: integer
    description: Year to start data scanning from
    default: 1959
    required: false
  YearEndParam:
    name: end
    in: query
    type: integer
    description: Year to finish data scanning
    default: 2100
    required: false
  MonthParam:
    name: month
    in: query
    type: array
    items:
      type: integer
    description: Month(s) to select, if not a whole year
    default: []
    required: false
  LatMinParam:
    name: lat_min
    in: query
    type: integer
    description: Latitude (min) to define the range (-90..90)
    default: -90
    required: false
  LatMaxParam:
    name: lat_max
    in: query
    type: integer
    description: Latitude (max) to define the range (-90..90)
    default: 90
    required: false
  RefMeasParam:
    name: ref_meas
    in: query
    type: string
    description: Reference observational measurument
    default: SBUV_GSFC_merged-SAT-ozone
    required: true
  RefYearParam:
    name: ref_year
    in: query
    type: integer
    description: Reference year for the obsevational measurement
    default: 1980
    required: true
paths:
  /apiinfo:
    get:
      operationId: o3api.api.get_api_info
      tags:
        - api
      summary: Returns information about the API
      description: Information about the API (o3api metadata)
      produces:
        - application/json
      responses:
        '200':
          description: Successfully returned o3api info
          schema:
            $ref: '#/definitions/ApiInfo'
        '404':
          description: Requested resource not found
  /data:
    get:
      operationId: o3api.api.get_data_types
      tags:
        - data
      summary: Returns a list of plot types with the available raw data
      description: List of plot types with the available raw data
      produces:
        - application/json
      responses:
        '200':
          description: Successfully returned the list of data types
          schema:
            $ref: '#/definitions/DataList'
        '404':
          description: Requested resource not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /data/tco3_zm:
    post:
      operationId: o3api.api.get_data_tco3_zm
      tags:
        - data
      summary: Returns raw data for tco3_zm
      description: Raw data to be processed for building tco3_zm plot
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/ModelsParamReq'
        - $ref: '#/parameters/YearBeginParam'
        - $ref: '#/parameters/YearEndParam'
        - $ref: '#/parameters/MonthParam'
        - $ref: '#/parameters/LatMinParam'
        - $ref: '#/parameters/LatMaxParam'
      responses:
        '200':
          description: Successfully retrieved the data
          schema:
            type: array
            items:
              $ref: '#/definitions/O3Data'
        '404':
          description: Requested resource not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /data/tco3_return:
    post:
      operationId: o3api.api.get_data_tco3_return
      tags:
        - data
      summary: Returns raw data for tco3_return
      description: Raw data to be processed for building tco3_return plot
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/ModelsParamReq'
        - $ref: '#/parameters/YearBeginParam'
        - $ref: '#/parameters/YearEndParam'
        - $ref: '#/parameters/MonthParam'
        - $ref: '#/parameters/LatMinParam'
        - $ref: '#/parameters/LatMaxParam'
      responses:
        '200':
          description: Successfully retrieved the data
          schema:
            type: array
            items:
              $ref: '#/definitions/O3Data'
        '404':
          description: Requested resource not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /models:
    get:
      operationId: o3api.api.get_models_list
      tags:
        - models
      summary: Returns a list of available models
      description: List of available models
      produces:
        - application/json
      parameters:
        - name: ptype
          in: query
          type: string
          description: 'Plot type (tco3_return, tco3_zm, vmro3_zm)'
          required: false
        - name: select
          in: query
          type: string
          description: 'Select models according to the {select} pattern'
          required: false
      responses:
        '200':
          description: Successfully returned list of models
          schema:
            $ref: '#/definitions/ModelsList'
        '404':
          description: Requested resource not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/models/{model}':
    get:
      operationId: o3api.api.get_model_detail
      tags:
        - models
      summary: Returns detailed information about a model
      description: Detailed information about a model
      produces:
        - application/json
      parameters:
        - name: model
          in: path
          type: string
          description: model name
          default: CCMI-1_ACCESS_ACCESS-CCM-refC2
          required: true
      responses:
        '200':
          description: Successfully returned model information
          schema:
            $ref: '#/definitions/ModelInfo'
        '404':
          description: Requested resource not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /models/plotstyle:
    post:
      operationId: o3api.api.get_plot_style
      tags:
        - models
      summary: Returns plot styles for models
      description: Plot styles for selected models and plot type
      produces:
        - application/json
      parameters:
        - name: ptype
          in: query
          type: string
          description: 'Plot type (tco3_return, tco3_zm, vmro3_zm)'
          required: false
        - $ref: '#/parameters/ModelsParam'
      responses:
        '200':
          description: Successfully returned plot styles for models
          schema:
            type: array
            items:
              $ref: '#/definitions/ModelsPlotStyle'
        '404':
          description: Requested resource not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /plots:
    get:
      operationId: o3api.api.get_plot_types
      tags:
        - plots
      summary: Returns a list of possible plots
      description: List of possible plots
      produces:
        - application/json
      responses:
        '200':
          description: Successfully returned the list of possible plots
          schema:
            $ref: '#/definitions/PlotsList'
        '404':
          description: Requested resource not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /plots/tco3_zm:
    post:
      operationId: o3api.api.plot_tco3_zm
      tags:
        - plots
      summary: Builds and returns tco3_zm plot
      description: tco3_zm plot or corresponding data points
      produces:
        - application/pdf
        - application/json
      parameters:
        - $ref: '#/parameters/ModelsParamReq'
        - $ref: '#/parameters/YearBeginParam'
        - $ref: '#/parameters/YearEndParam'
        - $ref: '#/parameters/MonthParam'
        - $ref: '#/parameters/LatMinParam'
        - $ref: '#/parameters/LatMaxParam'
        - $ref: '#/parameters/RefMeasParam'
        - $ref: '#/parameters/RefYearParam'
      responses:
        '200':
          description: Successfully created the plot
          schema:
            type: array
            items:
              $ref: '#/definitions/O3Data'
        '404':
          description: Requested resource not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /plots/tco3_return:
    post:
      operationId: o3api.api.plot_tco3_return
      tags:
        - plots
      summary: Builds and returns tco3_return plot
      description: tco3_return plot or corresponding data points
      produces:
        - application/pdf
        - application/json
      parameters:
        - $ref: '#/parameters/ModelsParamReq'
        - $ref: '#/parameters/MonthParam'
        - $ref: '#/parameters/LatMinParam'
        - $ref: '#/parameters/LatMaxParam'
        - $ref: '#/parameters/RefMeasParam'
        - $ref: '#/parameters/RefYearParam'
      responses:
        '200':
          description: Successfully created a plot
          schema:
            type: array
            items:
              $ref: '#/definitions/O3Data'
        '404':
          description: Requested resource not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  ApiInfo:
    type: object
    properties:
      author:
        type: string
      author-email:
        type: string
      home-page:
        type: string
      license:
        type: string
      name:
        type: string
      summary:
        type: string
      version:
        type: string
  DataList:
    type: array
    items:
      type: string
  ModelsList:
    type: array
    items:
      type: string
  ModelInfo:
    type: object
    properties:
      model:
        type: string
      tco3_zm:
        $ref: '#/definitions/ModelInfoObj'
      tco3_return:
        $ref: '#/definitions/ModelInfoObj'
      vmro3_zm:
        $ref: '#/definitions/ModelInfoObj'
  ModelInfoObj:
    type: object
    properties:
      data:
        type: object
      isdata:
        type: boolean
      plotstyle:
        type: object
  ModelsPlotStyle:
    type: object
    properties:
      model:
        type: string
      tco3_zm:
        $ref: '#/definitions/ModelsPlotStyleObj'
      tco3_return:
        $ref: '#/definitions/ModelsPlotStyleObj'
      vmro3_zm:
        $ref: '#/definitions/ModelsPlotStyleObj'
  ModelsPlotStyleObj:
    type: object
    properties:
      plotstyle:
        type: object
  PlotsList:
    type: array
    items:
      type: string
  O3Data:
    type: object
    properties:
      model:
        type: string
      plotstyle:
        type: object
      x:
        type: array
        items:
          type: number
      y:
        type: array
        items:
          type: number
  Error:
    type: string